hw06 done
zaz600/otus_go_hw pull request #10
Opened 2020-10-23 20:52 UTC by zaz600

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-10-28 16:47 UTC, kulti approved these changes
Все супер. ДЗ принято - 10/10.

2020-10-28 17:12 UTC, kulti requested changes
А нет, не супер :)

Есть небольшая ошибочка. Предлагаю ее поправить.

2020-10-28 17:12 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Тут возможет кейз, когда из out больше никто не будет читать. Тогда эта горутина зависнет навсегда.

2020-10-28 19:34 UTC, zaz600 commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Спасибо, добавил отправку через select

2020-10-28 19:34 UTC, zaz600 commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Спасибо, сделал отправку через select

2020-10-29 17:19 UTC, kulti approved these changes
Теперь точно все :)

2020-10-29 19:43 UTC, merged