HW2 is completed
zaz600/otus_go_hw pull request #2
Opened 2020-08-31 18:25 UTC by zaz600

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-09-05 07:55 UTC, kulti requested changes
Довольно сложное решение. Используются 4 символа (предыдущий, текущий, следующий и послеследующий).

Есть одна сомнительная проверка, добавьте на нее, пожалуйста, тесткейз.

Также, пока разбирался, нашел, что функция неправильно работает для случая `\\\`. Должна быть ошибка.

2020-09-05 07:55 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		case currentChar != escapeChar && !unicode.IsDigit(currentChar):
В проверке `currentChar != escapeChar` нет смысла, т.к. это уже проверено вышестоящим case.

2020-09-05 07:55 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			if i == lastIndex && getOrDefault(runes, lastIndex-1, zeroByte) != escapeChar {
Не очень понимаю эту проверку. Примеры, вроде не подходят под нее, т.к. в конце должен быть `\`. В тестах этих примеров тоже нет.

Честно говоря, непонятно, в каком случае `getOrDefault(runes, lastIndex-1, zeroByte) != escapeChar` может быть false. Если выкинуть эту часть условия, то все тесты продолжат работать.

2020-09-05 08:03 UTC, zaz600 commented on hw02_unpack_string/unpack.go
> +			if i == lastIndex && getOrDefault(runes, lastIndex-1, zeroByte) != escapeChar {
`Честно говоря, непонятно, в каком случае getOrDefault(runes, lastIndex-1, zeroByte) != escapeChar`
 для `aab\` в случае, когда цикл находится на символе `\`

В целом, понятно, что решение вышло сложновато, попробую переделать, спасибо

2020-09-05 08:41 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			if i == lastIndex && getOrDefault(runes, lastIndex-1, zeroByte) != escapeChar {
Решение можно не переделывать. Главное зафиксировать этот случай в тестах и пофиксить случай `\\\`.

2020-09-05 11:13 UTC, zaz600 commented on hw02_unpack_string/unpack.go
> +			if i == lastIndex && getOrDefault(runes, lastIndex-1, zeroByte) != escapeChar {
Спасибо, но я все же переделал 00cd5f8.

В изначальном варианте для кейса с тремя слешами, пришлось бы делать костыль вида "если слеш последний, а перед ним еще слеш, который сам незаэскейплен, то..."

2020-09-05 11:16 UTC, zaz600 commented on hw02_unpack_string/unpack.go
> +// Флажки для состояния циклf. Вместо двух bool.
```suggestion
// Флажки для состояния цикла. Вместо двух bool.
```

2020-09-05 12:37 UTC, kulti requested changes
Решение стало сильно лучше и понятнее. Осталось починить один случай.

2020-09-05 12:37 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +			expected: `x`,
Это странно. Эскейпить можно только цифру и слэш.

2020-09-05 12:37 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	}
Можно просто buff.WriteRune(char) в цикле сделать, тогда не нужно проверять значение repeat.

2020-09-05 13:22 UTC, zaz600 commented on hw02_unpack_string/unpack.go
> +	}
Тогда в коде не будет использоваться `strings.Repeat`, который упомянут в задании.
Или то, что там упоминается - рекомендация, а не требование?

2020-09-05 13:23 UTC, zaz600 commented on hw02_unpack_string/unpack_test.go
> +			expected: `x`,
Поправил 2954135836ecf946cb33529c4fa3aa0d3f15228c

2020-09-05 13:30 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	}
Вы про то, что в секции **Подсказки**? Там просто собраны ссылки и методы, чтобы не велосипедить, чтобы показать, в каком направлении думать над решением. Вы всегда можете придумать решение, в котором их не будет.

2020-09-05 13:38 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		case flags&ESCAPE == ESCAPE && !unicode.IsDigit(char) && char != escapeChar &&
Это очень сложное условие. В нем легко запутаться и что-то упустить. Например, не учтен случай "a\x"

2020-09-05 13:38 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	}
Проверка `repeat > 0` теперь тоже не имеет смысла.

2020-09-05 14:50 UTC, zaz600 commented on hw02_unpack_string/unpack.go
> +		case flags&ESCAPE == ESCAPE && !unicode.IsDigit(char) && char != escapeChar &&
И правда 4b4966e1bbfebcfdf4b83a8154862d2bf1fb53ba

2020-09-05 14:50 UTC, zaz600 commented on hw02_unpack_string/unpack.go
> +	}
fixed

2020-09-05 16:54 UTC, kulti approved these changes, later dismissed
Теперь похоже, что решение рабочее.

Код все еще не очень чистый. В swtich'e три кейза жонглируют одними и теми же условиями. Думаю, с практикой будет получаться все лучше и лучше.

ДЗ принято - 9/10.

2020-09-05 18:10 UTC, zaz600 commented
Спасибо. В текущем алгоритме, без дублирования в case флагов будет больше ветвлений: 
- флаг есть
  - буква
  - цифра
  - слеш
- флага нет
  - буква
  - цифра
  - слеш

Ну или наоборот
- буква
  - флаг есть
  - флага неи
цифра
  - флаг есть
  - флага нет
- слеш
  - флаг есть
  - флага нет

2020-09-05 19:10 UTC, kulti commented
Больше ветвлений != сложнее код.

В предложенных вариантах все кейзы как на ладони. Сразу видно, что и когда произойдет. В текущем же варианте решения нужно призадуматься, какие кейзы обработаны и что именно попадет в default.

Иногда, когда распишешь в лоб каждый "if'чик", то сразу видишь, как их можно логично сгруппировать. Но это вроде не тот случай - здесь нет очевидного уменьшения ветвления без потери ясности.

2020-09-05 19:45 UTC, zaz600 commented
Согласен. 
Немного порефакторил и упростил условия. Для читабельности убраны битовые флаги в пользу bool-переменных.

2020-09-06 12:56 UTC, kulti approved these changes
Теперь код легко читается. Поднял баллы до 10.

2020-09-06 13:01 UTC, merged